version: '3'
networks:
  demo_network:
    driver: bridge
services:
  clickhouse:
      image: clickhouse/clickhouse-server
      container_name: clickhouse-server
      volumes:
        - ./data:/var/lib/clickhouse
      ports:
        - "9000:9000"
        - "18123:8123"
      ulimits:
        nproc: 65535
        nofile:
          soft: 262144
          hard: 262144
      networks: 
        - demo_network